### PR TITLE
[DOCS] Build website

### PR DESCRIPTION
**Pull request by pan3793**
# [BUG]/[FEATURE] title

### What changes were proposed in this pull request?

image

### What are the items that need reviewer attention?

image

### How was this patch tested?

/cc @related-reviewer

/assign @main-reviewer

### CODE REVIEW

**Comment by pan3793** [comment]
image
image
I propose two styles for configuration, please let me know which one the community is prefered.

**Comment by pan3793** [comment]
After offline discussion, the table format is adopted.

**Comment by pan3793** [comment]
ping @waitinfuture @AngersZhuuuu

**Comment by waitinfuture** [comment]
LGTM, thanks!

**Review by waitinfuture — APPROVED** [review]

**Pull request merged**
