### PR TITLE
[ISSUE-637][FEATURE] Change CheckAlive to CheckAvailable and reply checkQuota result

### PR DESCRIPTION
**Pull request by AngersZhuuuu**
### Related issues.
https://github.com/alibaba/RemoteShuffleService/issues/637

### How was this patch tested?

/cc @related-reviewer

/assign @main-reviewer

### CODE REVIEW

**Comment by AngersZhuuuu** [comment]
ping @waitinfuture

**Comment by AngersZhuuuu** [comment]
Should we use `CheckQuota` to replace `CheckAvailable`?

**Comment by waitinfuture** [comment]
> 

I prefer CheckQuota

**Comment by AngersZhuuuu** [comment]
> > 
> 
> I prefer CheckQuota

updated

**Review by waitinfuture — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
